### ISSUE TITLE
does not work with storybook 8

### ISSUE THREAD

**Issue by ayZagen** [Sidnioulz/storybook-addon-vue-mdx#3] opened 2024-05-07 12:16 UTC
```

WARN The following packages are incompatible with Storybook 8.0.10 as they depend on different major versions of Storybook packages:
WARN - storybook-addon-vue-mdx@0.1.5
WARN 
WARN 
WARN Please consider updating your packages or contacting the maintainers for compatibility details.
WARN For more on Storybook 8 compatibility, see the linked GitHub issue:
WARN https://github.com/storybookjs/storybook/issues/26031

```

**Comment by Sidnioulz** [comment] 2024-07-16 17:55
Hey folks, I missed this email 😱 It seems @Romainpetit has a PR ready, if not I will fix this tomorrow night. Thanks for your patience!

**Comment by Sidnioulz** [comment] 2024-07-17 16:47
#5 has been merged and should hopefully close this issue. Thank you @Romainpetit!

@Romainpetit @ayZagen, I would be grateful if either of you could confirm that the problem is fixed with the latest release in your respective stacks. If it is not fixed, please reopen the issue.

**Closed by Sidnioulz** 2024-07-17 16:47 UTC
Labels: bug, major

**Comment by Romainpetit** [comment] 2024-07-18 08:22
The support of latest Storybook versions works great! 

However, we could downgrade the Storybook group version of this addon to `8.0.0`, so that it appears as compatible with any "Storybook 8 and up" projects.

**Comment by Sidnioulz** [comment] 2024-07-22 09:23
Good point, though, that would mean testing it on SB 8.0.0 specifically :)

I've asked the team at SB if we should specifically target 8.0.0 out of curiosity. I'll do the cleanup and release work, eventually, and that eventually will be much sooner if they confirm we need to address that. My intuition is that almost everyone migrates to the latest anyway because that's what the upgrade command does.
